---
# This file tells https://pre-commit.com/
# which hooks are provided by this repo
# for use by other git repos.

- id: yamlfmt
  name: Format YAML files
  description: Format YAML files
  entry: yamlfmt
  language: python
  types:
  - yaml
  additional_dependencies:
  - ruamel.yaml
