#!/usr/bin/env python3
"""Format YAML files."""

import argparse
import sys
from ruamel.yaml import YAML  # pylint: disable=import-error

DEFAULT_INDENT = {
    "mapping": 4,
    "sequence": 6,
    "offset": 4,
    }


class Cli:
    # pylint: disable=too-few-public-methods
    """ command-line-interface """

    def __init__(self):
        """ initialize the CLI """
        parser = argparse.ArgumentParser(
            description="Format YAML files",
            formatter_class=argparse.ArgumentDefaultsHelpFormatter,
            epilog="Tips at https://yaml.readthedocs.io/en/latest/detail.html",
            )
        parser.add_argument(
            "-m",
            "--mapping",
            type=int,
            default=DEFAULT_INDENT["mapping"],
            help="number of spaces to indent mappings (dictionaries)",
            )
        parser.add_argument(
            "-s",
            "--sequence",
            type=int,
            default=DEFAULT_INDENT["sequence"],
            help="number of spaces to indent sequences (arrays/lists)",
            )
        parser.add_argument(
            "-o",
            "--offset",
            type=int,
            default=DEFAULT_INDENT["offset"],
            help="number of spaces to offset the dash from sequences",
            )
        parser.add_argument(
            "-c",
            "--colons",
            action="store_true",
            help="whether to align top-level colons",
            )
        parser.add_argument(
            "-w",
            "--width",
            type=int,
            default=150,
            help="maximum line width",
            )
        parser.add_argument(
            "-p",
            "--preserve-quotes",
            action="store_true",
            help="whether to keep existing string quoting"
            )
        parser.add_argument(
            "-e",
            "--explicit-start",
            action="store_true",
            help="whether to add an explicit document start"
            )
        parser.add_argument(
            "file_names",
            metavar="FILE_NAME",
            nargs="*",
            help="space-separated list of YAML file names",
            )
        self.parser = parser


class Formatter:
    """
    Reformat a yaml file with proper indentation.
    Preserve comments.
    """
    def __init__(self, **kwargs):
        yaml = YAML()
        yaml.indent(
            mapping=kwargs.get("mapping", DEFAULT_INDENT["mapping"]),
            sequence=kwargs.get("sequence", DEFAULT_INDENT["sequence"]),
            offset=kwargs.get("offset", DEFAULT_INDENT["offset"]),
            )
        yaml.top_level_colon_align = kwargs.get("colons", False)
        yaml.explicit_start = kwargs.get("explicit_start", True)
        yaml.width = kwargs.get("width", None)
        yaml.preserve_quotes = kwargs.get("preserve_quotes", False)

        self.yaml = yaml
        self.path = kwargs.get("path", None)
        self.content = list({})

    def format(self, path=None):
        """ Read file and write it out to same path """
        if not path:
            path = self.path
        print(path, end="")
        FORMATTER.parse_file(path)
        FORMATTER.write_file(path)
        print("  Done")

    def parse_file(self, path=None):
        """ Read the file """
        if not path:
            path = self.path
        try:
            with open(path, "r") as stream:
                self.content = list(self.yaml.load_all(stream))
        except IOError:
            self.fail(f"Unable to read {path}")

    def write_file(self, path=None):
        """ Write the file """
        if not path:
            path = self.path
        try:
            with open(path, "w") as stream:
                self.yaml.dump_all(self.content, stream)
        except IOError:
            self.fail(f"Unable to write {path}")

    @staticmethod
    def fail(msg):
        """ Abort """
        sys.stderr.write(msg)
        sys.exit(1)


if __name__ == "__main__":
    ARGS = Cli().parser.parse_args()
    FORMATTER = Formatter(
        mapping=ARGS.mapping,
        sequence=ARGS.sequence,
        offset=ARGS.offset,
        colons=ARGS.colons,
        width=ARGS.width,
        preserve_quotes=ARGS.preserve_quotes,
        explicit_start=ARGS.explicit_start
        )
    for file_name in ARGS.file_names:
        FORMATTER.format(file_name)
